sudo: required
dist: bionic
language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --save
- yarn upgrade --latest
script:
  - CI=false yarn build
  
deploy:
- provider: pages
  skip-cleanup: true
  github-token: ${GitHubKEY}
  local-dir: build
  on:
    branch: master