language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_script:
  - yarn install

script:
  - yarn build
  
deploy:
- provider: pages
  skip-cleanup: true
  github-token: ${GitHubKEY}
  keep-history: true
  email: ${GitHubEmail}
  name: ${GitHubName}
  local-dir: ./build
  on:
    branch: master