language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn install

script:
  - CI=false yarn build
  
deploy:
- provider: pages
  skip-cleanup: true
  github-token: ${GitHubKEY}
  local-dir: build
  on:
    branch: master